apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: crypto-calculator-dev
deploy:
  kubeContext: minikube
  kubectl:
    manifests:
      - "k8s/*.yaml"
build:
  artifacts:
    - image: crypto-calculator
      context: .
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
          - "**/*.py"
portForward:
  - resourceType: service
    resourceName: crypto-calculator
    port: 80
    localPort: 80
