apiVersion: v1
kind: Service
metadata:
  name: crypto-calculator-service
spec:
  type: ClusterIP
  selector:
    app: crypto-calculator
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
